FROM node:17-alpine3.12

# diretoria onde a aplicação vai estar
WORKDIR /usr/src/app  

# copiar para usr/src/app, o package.json
COPY package*.json ./
COPY server.js ./
COPY ./seedDB.js ./

# install production dependencies   
RUN npm i --only=production

COPY ./src ./src
COPY ./api-docs ./api-docs

EXPOSE 5001

# executar npm start em /usr/src/app (WORKDIR)
CMD npm start 
